version: '3.7'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    container_name: vaultwarden
    env_file: .env
    volumes:
      - "./data:/data:rw"
    ports:
      - "5000:80"
